title: Wild Fig Research
email: hello@wildfigresearch.org.uk
description: >-
  Wild Fig Research is an independent research organisation helping public
  sector and mission-led organisations understand their users, test their
  services, and evaluate their impact.
baseurl: ""
url: "https://wildfigresearch.org.uk"

collections:
  projects:
    output: true
    sort_by: date

defaults:
  - scope:
      path: ""
      type: projects
    values:
      sitemap: false

plugins:
  - jekyll-sitemap

destination: docs/
