title: Wild Fig Research
email: hello@wildfigresearch.org.uk
description: >-
  Wild Fig Research is a Sheffield-based organisation working with
  communities, VCFSE organisations, universities and the public sector on
  participatory research.
baseurl: ""
url: "https://wildfigresearch.org.uk"

collections:
  projects:
    output: true
    sort_by: date
  team:
    output: true

defaults:
  - scope:
      path: ""
      type: projects
    values:
      sitemap: false

plugins:
  - jekyll-sitemap

destination: docs/
